name: PHPStan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  phpstan:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variants: [ {typo3: 12.4, php: 8.2}, {typo3: 13.4, php: 8.4}, {typo3: 14.3, php: 8.4}, {typo3: 14.3, php: 8.5}  ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Fix git ownership (needed for php-actions/composer@v6)
        run: git config --global --add safe.directory /app

      - name: Install dependencies
        run: |
          if [ "${{ matrix.variants.typo3 }}" = "12.4" ]; then
            cp composer.lock.v12 composer.lock
          fi
          if [ "${{ matrix.variants.typo3 }}" = "12.4" ]; then
            composer install --no-scripts --ignore-platform-reqs
          else
            composer update --no-scripts --ignore-platform-reqs --with=typo3/cms-core:^${{ matrix.variants.typo3 }}
          fi
        shell: bash

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          configuration: ./.github/phpstan_${{ matrix.variants.typo3 }}.neon
          path: ''
